FROM postgres:14

ENV POSTGRES_USER llf
ENV POSTGRES_PASSWORD Aa11111111
ENV POSTGRES_DB postgres

# COPY ./confs/postgresql/init-user-db.sh /docker-entrypoint-initdb.d/
# ADD ./confs/postgresql/public.sql /docker-entrypoint-initdb.d/

EXPOSE 5432
